!Khiasmos.scl
!
Khiasmos in the 22-tone scale of India
22
!
256/243
!Persian
135/128
16/15
10/9
9/8
32/27
!Persian
1215/1024
6/5
5/4
81/64
4/3
27/20
45/32
729/512
3/2
128/81
!Persion
405/256
8/5
5/3
27/16
16/9
9/5
15/8
243/128
2/1
! Created with the iOS app "Wilsonic" by Marcus Hobbs
!
! Khiasmos in the 22-tone scale of India.
! (C) 1999,2005 by Ervin McDonald Wilson

! Please see the Scala archives at: http://www.huygens-fokker.org/docs/scalesdir.txt
